# Generated by Django 3.1.1 on 2020-09-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
